# 2024.12.27  
사용한 모듈: numpy, pandas   
첨부파일: data/heroes.csv  

넘파이, 판다스 실습  

### 조건부 표현식

In [1]:
score = 100

if score >= 60:
    message = "success"
else:
    message = "failure"

print(message)

score = int(input("score? : "))

message = "success" if score >= 60 else "failure"

print(message)

success
failure


### 리스트 컴프리헨션  
[표현식 for 항목 in iterable]

In [2]:
numbers = [1,2,3,4,5]
squares = []
for x in numbers:
    squares.append(x**2)

print(squares)

squares = [x**2 for x in numbers]
print(squares)

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


In [3]:
numbers = [1,2,3,4,5,6,7]
# even_numbers = [("" if x%2 else x) for x in numbers]
even_numbers = [x**2 for x in numbers if not(x%2)]
print(even_numbers)

[4, 16, 36]


### NumPy  
python list: 주소값을 가리키는 포인터  
numpy array: 실제 배열값을 가지고 있는 배열

In [4]:
# pip install numpy

In [5]:
import numpy as np

np.__version__

'2.2.1'

In [6]:
a_list = [1,2,3,4]
print(type(a_list))

num_list = [1,2,3,4]
int_arr2 = np.array(num_list)

print(type(num_list))
print(type(int_arr2))
print(int_arr2)

<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [7]:
list_data = [1, 2., 3, '3']

arr = np.array(list_data)

print(arr)
print(type(arr))
print(type(arr[0]))
print(arr.shape)

['1' '2.0' '3' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
(4,)


In [8]:
arr1 = np.arange(1, 10, 2)

arr1

array([1, 3, 5, 7, 9])

In [9]:
np.zeros(10, dtype=int)
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)
print(arr.ndim) # 배열 차원 수
print(arr.shape) # 배열 차원의 크기 튜플로 리턴
print()

arr = np.array([[[1,2,3,4],[5,6,7,8]],
                [[17,18,19,20],[21,22,23,24]],
                [[9,10,11,12],[13,14,15,16]]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(len(arr[0]))
print(len(arr[0][0]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(3, 2, 4)
3
2
4


In [11]:
arr = np.arange(1,11)
print(arr)

print(arr.reshape(-1,2))
print(arr.reshape(5, -1))
# print(arr.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
a = [1,2,3]
b = [4,5,6]

print(type(a), type(b))
print(a+b)
print()

arr_a = np.array(a)
arr_b = np.array(b)

print(type(arr_a), type(arr_b))
print(arr_a + arr_b)
print(arr_a - arr_b)
print(arr_a * arr_b)
print(arr_a / arr_b)

<class 'list'> <class 'list'>
[1, 2, 3, 4, 5, 6]

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
data = [0,1,2,3,4,5,6,7,8,9]
data1 = []
data2 = []

for d in data :
    data1.append(d*2)
print(data1)

data2 = [d*2 for d in data]
print(data2)

arr_d = np.array(data)
print(arr_d *2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
c = np.array([[0,2,3],[3,4,5]])
print(len(c))
print(len(c[0]))
print(c.shape)
print(c.ndim)
print(c.size)

2
3
(2, 3)
2
6


In [15]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [16]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a[0,0], a[0,1], a[-1,-1])
# print(a[:,-1:2])
print("="*20)
print(a[0])
print(a[:, 1])
print(a[1, 1:])
print(a[:2, :2])

0 1 7
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [17]:
a= np.array([1,2,3])
b=np.array([10,20,30])

print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


#### 팬시 인덱싱(fancy indexing)  
불리언 방식  : 원래 배열의 사이즈와 맞아야함
정수 배열 인덱싱 방식 : 원래 배열의 사이즈와 상관없음

In [18]:
a = np.arange(0,10)
idx = np.array([True, False, True, False, True, False,True,False,True,False])

print(a[idx])
print(a[a%2==0])
print(a[a>4])

[0 2 4 6 8]
[0 2 4 6 8]
[5 6 7 8 9]


In [19]:
a = np.arange(1,10) * 11
idx = np.array([0,2,4,6,8])
print(a[idx])

idx = np.array([5,5,5, 0,0,0,0,1,1,1,1,2,2,2,2,6,6,6])
print(a[idx])


[11 33 55 77 99]
[66 66 66 11 11 11 11 22 22 22 22 33 33 33 33 77 77 77]


In [20]:
a = np.arange(1, 13)
a = a.reshape(3,-1)
print(a)
# a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(a[:, [True, False, False, True]])
print(a[:, [0,-1]])
print(a[:, [0,3]])

print(a[[2,0,1]])
# print(a[::-1]) # 역순 출력

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [21]:
x = np.arange(1,21)
x
# bo = 
print(x[x%3==0])
print(x[x%4==1])

tempX = x[x%3==0]
print(tempX[tempX%4==1])


[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## Pandas 데이터구조  

In [22]:
# pip install pandas

In [23]:
import pandas as pd

pd.__version__

'2.2.3'

In [24]:
s = pd.Series([3, -5, 7, 4],index=['a', 'b', 'c', 'd'])

print(s)
print(type(s))
print(s.index)
print(s.values)
print(s['a'])
# print(s[0]) # FuturWarning

# for i in list(s.index) :
#     print(s[i], end=' ')

s * 3

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>
Index(['a', 'b', 'c', 'd'], dtype='object')
[ 3 -5  7  4]
3


a     9
b   -15
c    21
d    12
dtype: int64

In [25]:
df = pd.DataFrame([['']])

In [26]:
df = pd.DataFrame({'Division': ['부산광역시', '전라남도', '강원도'],
                   'Code': ['051', '061', '033'],
                   'Population': [3364358, 1840921, 1525530]
                   })

print(type(df))
print(df)
display(df)
print(df.index)
print(df.columns)

df.info()
df.set_index('Division')

<class 'pandas.core.frame.DataFrame'>
  Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1525530


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1525530

RangeIndex(start=0, stop=3, step=1)
Index(['Division', 'Code', 'Population'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


Code  Population
Division                 
부산광역시     051     3364358
전라남도      061     1840921
강원도       033     1525530

In [27]:
df = pd.DataFrame([['부산광역시', '051', 3364358],
                   ['전라남도', '061', 1840921],
                   ['강원도', '033', 1535530]])

df.columns = ['Division', 'Code', 'Population']
print(df.columns)
print(df.keys)
print(df.values)
display(df)
df.info()

Index(['Division', 'Code', 'Population'], dtype='object')
<bound method NDFrame.keys of   Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530>
[['부산광역시' '051' 3364358]
 ['전라남도' '061' 1840921]
 ['강원도' '033' 1535530]]


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [28]:
df = pd.read_csv("data/heroes.csv")
pd.options.display.float_format = '{:.0f}'.format # 표현식 바꾸기

display(df)
df.info()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [29]:
display(df.head(3))
display(df.tail(2))


이름  나이    직업     국적    키          재산
0   아이언맨  58   CEO     미국  174 11500000000
1     토르  45     신  아스가르드  190         NaN
2  스파이더맨  18  고등학생     미국  177         600

이름  나이   직업   국적    키        재산
5   캡틴마블  25  파일럿   미국  170 340000000
6  블랙위도우  32  스파이  러시아  170  50000000

##### describe()  
숫자로 처리할 수 있는 열만  
통계치 보여줌

In [30]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [31]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [32]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [33]:
df['나이'].nlargest(7)

0    58
1    45
4    33
6    32
3    27
5    25
2    18
Name: 나이, dtype: int64

In [34]:
df.nlargest(3, '나이')

이름  나이     직업     국적    키          재산
0  아이언맨  58    CEO     미국  174 11500000000
1    토르  45      신  아스가르드  190         NaN
4    헐크  33  핵물리학자     미국  270  1000000000

### 팬시인덱싱 사용

In [35]:
df[['이름','직업', '나이']].nlargest(7, '나이')

이름     직업  나이
0   아이언맨    CEO  58
1     토르      신  45
4     헐크  핵물리학자  33
6  블랙위도우    스파이  32
3   원더우먼     공주  27
5   캡틴마블    파일럿  25
2  스파이더맨   고등학생  18

In [36]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [37]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

### iloc 인덱스를 이용해 데이터 가져오기

In [38]:
display(df.iloc[0])
print(type(df.iloc[0]))

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: 0, dtype: object

<class 'pandas.core.series.Series'>


In [39]:
print(type(df.iloc[[1,3,4]]))

df.iloc[:5, :3]

<class 'pandas.core.frame.DataFrame'>


이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [40]:
df2 = df.copy()
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [41]:
df2.loc['a':'b']

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [42]:
df2.loc['a':'b', '이름':'직업']

이름  나이   직업
a  아이언맨  58  CEO
b    토르  45    신

In [43]:
print(df.isnull().sum())

isN = df['재산'].isnull()
df[isN]

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64


이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [44]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [45]:
df.loc[(df['나이'] > 30)&(df['나이']<50), '이름':'직업'] 

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [46]:
df.sort_values('키') # 오름차순
df.sort_values('키',ascending=False) # 내림차순

이름  나이     직업     국적    키          재산
4     헐크  33  핵물리학자     미국  270  1000000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN
2  스파이더맨  18   고등학생     미국  177         600
0   아이언맨  58    CEO     미국  174 11500000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [47]:
df2['국적'] = '대한민국'
df2['전투력'] = [90, 100,46, 79, 89, 78, 65]
df2['전투력'] -= 5
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   85
b     토르  45      신  대한민국  190         NaN   95
c  스파이더맨  18   고등학생  대한민국  177         600   41
d   원더우먼  27     공주  대한민국  178         NaN   74
e     헐크  33  핵물리학자  대한민국  270  1000000000   84
f   캡틴마블  25    파일럿  대한민국  170   340000000   73
g  블랙위도우  32    스파이  대한민국  170    50000000   60

In [48]:
df2.columns = ['성명', '연령', '하는 일', '소속', '신장', '자산', '파워']
df2.columns
df2 

성명  연령   하는 일    소속   신장          자산  파워
a   아이언맨  58    CEO  대한민국  174 11500000000  85
b     토르  45      신  대한민국  190         NaN  95
c  스파이더맨  18   고등학생  대한민국  177         600  41
d   원더우먼  27     공주  대한민국  178         NaN  74
e     헐크  33  핵물리학자  대한민국  270  1000000000  84
f   캡틴마블  25    파일럿  대한민국  170   340000000  73
g  블랙위도우  32    스파이  대한민국  170    50000000  60

#### 데이터 프레임 다루기
1. dropna로 NaN 값이 있는 로우 삭제
2. dropna로 NaN 값이 있는 컬럼 삭제
3. 특정 컬럼 평균 구하기

In [49]:
# df2.drop(index=['a'], inplace=True)
# df2.drop(columns=['파워'], inplace=True)

df3 = df2.drop(index=['a'], columns=['파워'])
display(df3)
display(df3.dropna())
display(df3.dropna(axis=1))
# display(df3.fillna(0))
# display(df3.fillna(method="bfill"))
display(df3['자산'].fillna(df3['자산'].mean()))

성명  연령   하는 일    소속   신장         자산
b     토르  45      신  대한민국  190        NaN
c  스파이더맨  18   고등학생  대한민국  177        600
d   원더우먼  27     공주  대한민국  178        NaN
e     헐크  33  핵물리학자  대한민국  270 1000000000
f   캡틴마블  25    파일럿  대한민국  170  340000000
g  블랙위도우  32    스파이  대한민국  170   50000000

성명  연령   하는 일    소속   신장         자산
c  스파이더맨  18   고등학생  대한민국  177        600
e     헐크  33  핵물리학자  대한민국  270 1000000000
f   캡틴마블  25    파일럿  대한민국  170  340000000
g  블랙위도우  32    스파이  대한민국  170   50000000

성명  연령   하는 일    소속   신장
b     토르  45      신  대한민국  190
c  스파이더맨  18   고등학생  대한민국  177
d   원더우먼  27     공주  대한민국  178
e     헐크  33  핵물리학자  대한민국  270
f   캡틴마블  25    파일럿  대한민국  170
g  블랙위도우  32    스파이  대한민국  170

b    347500150
c          600
d    347500150
e   1000000000
f    340000000
g     50000000
Name: 자산, dtype: float64